version: '3.8'
services:
  database:
    image: 'mongo'
    container_name: 'mongoDB'
    restart: always
    environment: 
      - MONGO_INITDB_DATABASE=$DATABASE_NAME
      - MONGO_INITDB_ROOT_USERNAME=$DATABASE_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$DATABASE_PASSWORD
    volumes: 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - $DATABASE_DATA_PATH:/data/db
    networks: 
      - backend
  app:
    depends_on: 
      - database
    image: 'dw'
    container_name: 'app'
    restart: 'always'
    networks: 
      - backend

networks: 
  backend: